src/Entity/Employee.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\EmployeeRepository")
 */
class Employee
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $name;

    /**
     * @ORM\Column(type="date")
     */
    private $date_of_birth;

    /**
     * @ORM\Column(type="string", length=1)
     */
    private $gender;

    /**
     * @ORM\Column(type="string",nullable=true)
     *
     * @Assert\File(mimeTypes={ "image/*" })
     */
    private $photo;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $notes;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(\DateTimeInterface $date_of_birth): self
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getPhoto()
    {
        return $this->photo;
    }

    public function setPhoto($photo)
    {
        $this->photo = $photo;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }
}

src/Form/EmployeeType.php
<?php

namespace App\Form;

use App\Entity\Employee;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmployeeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('date_of_birth', DateType::class, ['label' => "Date Of Birth", 'attr' => []])
            ->add(
                'gender',
                ChoiceType::class,
                [
                    'choices' => [
                        "Male" => "M",
                        "Female" => "F",
                        "Others" => "O",
                    ],
                ]
            )
            ->add('photo', FileType::class, ['label' => "Profile Picture", 'data_class' => null])
            ->add('notes', TextareaType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => Employee::class,
            ]
        );
    }
}

src/Controller/EmployeeController.php
<?php

namespace App\Controller;

use App\Entity\Employee;
use App\Form\EmployeeType;
use App\Repository\EmployeeRepository;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/employee")
 */
class EmployeeController extends AbstractController
{
    /**
     *
     * @Route("/list/{page}", name="employee_index", methods={"GET"}, defaults={"page": 1} , requirements={"page"="\d+"})
     * @Security("is_granted('ROLE_ADMIN')")
     * @throws \Exception
     */
    public function index(
        EmployeeRepository $employeeRepository,
        Request $request,
        PaginatorInterface $paginator,
        $page = 1
    ): Response {
        $searchCriteria = $request->query->all();
        $employeeQuery = $employeeRepository->getQueryBySearchCriteria($searchCriteria);
        // Paginate the results of the query
        $employees = $paginator->paginate(
        // Doctrine Query, not results
            $employeeQuery,
            // Define the page parameter
            $page,
            // Items per page
            2
        );

        return $this->render(
            'employee/index.html.twig',
            [
                'employees' => $employees,
                'search' => $searchCriteria,
            ]
        );

    }

    /**
     * @Route("/new", name="employee_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $employee = new Employee();
        $form = $this->createForm(EmployeeType::class, $employee);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $employee->getPhoto();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            try {
                $file->move(
                    $this->getParameter('upload_directory'),
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }

            // updates the 'brochure' property to store the PDF file name
            // instead of its contents
            $employee->setPhoto($fileName);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($employee);
            $entityManager->flush();
            $this->addFlash('success', "Data has been added successfully");
            //this is test
            return $this->redirectToRoute('employee_index');
        }

        return $this->render(
            'employee/new.html.twig',
            [
                'employee' => $employee,
                'form' => $form->createView(),
            ]
        );
    }

    /**
     *
     * @Route("/report", name="employee_report", methods={"GET"})
     * @Security("is_granted('ROLE_ADMIN')")
     * @throws \Exception
     */
    public function showReport(EmployeeRepository $employeeRepository): Response
    {
        $employees = $employeeRepository->getGenderWiseEmployee();

        return $this->render(
            'employee/report.html.twig',
            [
                'employee_list' => $employees,
            ]
        );
    }

    /**
     *
     * @Route("/thirdparty", name="api_consumer", methods={"GET"})
     * @Security("is_granted('ROLE_ADMIN')")
     * @throws \Exception
     */
    public function apiConsumer(): Response
    {
        $data = json_decode(
            file_get_contents("https://rxnav.nlm.nih.gov/REST/interaction/interaction.json?rxcui=341248")
        );
        
        return $this->render(
            'api-data/index.html.twig',
            [
                'minconceptitem' => $data->interactionTypeGroup[0]->interactionType[0]->minConceptItem,
                'interactionPair' => $data->interactionTypeGroup[0]->interactionType[0]->interactionPair,
            ]
        );
    }

    /**
     * @Security("is_granted('ROLE_ADMIN')")
     * @Route("/{id}", name="employee_show", methods={"GET"})
     */
    public function show(Employee $employee): Response
    {
        return $this->render(
            'employee/show.html.twig',
            [
                'employee' => $employee,
            ]
        );
    }

    /**
     * @Security("is_granted('ROLE_ADMIN')")
     * @Route("/{id}/edit", name="employee_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Employee $employee): Response
    {
        $form = $this->createForm(EmployeeType::class, $employee);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            // updates the 'brochure' property to store the PDF file name
            // instead of its contents

            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', "Data has been updated successfully");

            return $this->redirectToRoute(
                'employee_index',
                [
                    'id' => $employee->getId(),
                ]
            );
        }

        return $this->render(
            'employee/edit.html.twig',
            [
                'employee' => $employee,
                'form' => $form->createView(),
            ]
        );
    }

    /**
     * @Security("is_granted('ROLE_ADMIN')")
     * @Route("/{id}", name="employee_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Employee $employee): Response
    {
        if ($this->isCsrfTokenValid('delete'.$employee->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($employee);
            $entityManager->flush();
        }
        $this->addFlash('success', "Data has been deleted successfully");

        return $this->redirectToRoute('employee_index');
    }


}

templates/employee/_delete_form.html.twig
<form method="post" action="{{ path('employee_delete', {'id': employee.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employee.id) }}">
    <button class="btn btn-block btn-danger">Delete</button>
</form>

templates/employee/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-block btn-primary col-sm-2 float-left">{{ button_label|default('Save') }}</button>
    <div class="float-left col-sm-2"><a href="{{ path('employee_index') }}" class="btn btn-block btn-info">Back</a></div>
{{ form_end(form) }}

templates/employee/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Employee{% endblock %}

{% block body %}
    <h1>Edit Employee</h1>

    {{ include('employee/_form.html.twig', {'button_label': 'Update'}) }}

{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('employee') }}
{% endblock %}

templates/employee/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Employee index{% endblock %}
{% set genders = {'M':"Male",'F':'Female','O':"Others"} %}
{% block body %}
    <div class="card">
        <div class="card-header">
            <div class="float-left">
                <i class="fa fa-align-justify"></i> List of Employee
            </div>

            <div class="clearfix"></div>
            <form method="get">
                <div class="float-left col-4"><input type="text" name="name" value="{% if search['name'] is defined %}{{ search['name'] }}{% endif %}" placeholder="name" class="form-control"/> &nbsp;</div>
                <div class="float-left col-4"><input type="number" min="1" name="age" value="{% if search['age'] is defined %}{{ search['age'] }}{% endif %}" placeholder="Age" class="form-control"/> &nbsp;</div>
                <div class="float-left col-4"><input type="submit" class="btn btn-primary" value="Search" name="search" placeholder="Age" class="form-control"/> &nbsp;</div>
            </form> <div class="float-right"><a href="{{ path('employee_new') }}" class="btn btn-block btn-info">Add</a></div>
        </div>

        <div class="card-body">

            <table class="table">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Age</th>
                    <th>Gender</th>
                    <th>Photo</th>
                    <th>Notes</th>
                    <th>actions</th>
                </tr>
                </thead>
                <tbody>
                {% for employee in employees %}
                    <tr>
                        <td>{{ employee.id }}</td>
                        <td>{{ employee.name }}</td>
                        <td>{{ date('now').diff((date(employee.dateOfBirth))).format('%y years') }}</td>
                        <td>{{ genders[employee.gender] }}</td>
                        <td><img class="img-thumbnail" src="{{ asset('uploads') }}/{{ employee.photo }}" width="80px" alt="Profile picture of {{ employee.name }}"/></td>
                        <td>{{ employee.notes }}</td>
                        <td>
                            <a href="{{ path('employee_show', {'id': employee.id}) }}">show</a>
                            <a href="{{ path('employee_edit', {'id': employee.id}) }}">edit</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="7">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <nav aria-label="Page navigation example">
                {{ knp_pagination_render(employees) }}
            </nav>
        </div>
    </div>
{% endblock %}

templates/employee/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Employee{% endblock %}

{% block body %}
<div class="card">
    <div class="card-header">
        <h1>Create new Employee</h1>
    </div>
    <div class="card-body">
        {{ include('employee/_form.html.twig') }}
    </div>
    <div class="card-footer">

    </div>
</div>





{% endblock %}

templates/employee/report.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gender Wise Employee List{% endblock %}
{% set genders={'M':"Male",'F':"Female",'O':"Others"} %}
{% block body %}

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i> Gender Wise Employee List
                </div>
                <div class="card-body">
                    <table class="table table-responsive-lg table-align-middle table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Gender</th>
                            <th>Employee Count</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for employee in employee_list %}
                            <tr>
                                <td>{{ genders[employee.gender] }}</td>
                                <td>{{ employee.no_of_employee }}</td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="7">no records found</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/employee/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Employee{% endblock %}
{% set genders ={'M':"Male",'F':"Female",'O':"Others"} %}
{% block body %}
    <div class="card">
        <div class="card-header">
            <h1>Employee</h1>
        </div>

        <div class="card-body">

            <table class="table">
                <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ employee.id }}</td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>{{ employee.name }}</td>
                </tr>
                <tr>
                    <th>Date_of_birth</th>
                    <td>{{ employee.dateOfBirth ? employee.dateOfBirth|date('Y-m-d') : '' }}</td>
                </tr>
                <tr>
                    <th>Gender</th>
                    <td>{{ genders[employee.gender] }}</td>
                </tr>
                <tr>
                    <th>Photo</th>
                    <td><img src="{{ asset('uploads/') }}/{{ employee.photo }}"></td>
                </tr>
                <tr>
                    <th>Notes</th>
                    <td>{{ employee.notes }}</td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <span class="float-left"> <a href="{{ path('employee_index') }}"
                                         class="btn btn-info btn-block">Back</a></span>
            &nbsp;&nbsp;&nbsp;
            <span class="float-left"><a href="{{ path('employee_edit', {'id': employee.id}) }}"
                                        class="btn btn-block btn-primary">edit</a></span>
            &nbsp;&nbsp;&nbsp;
            <span class="float-left">{{ include('employee/_delete_form.html.twig') }}</span>
        </div>

    </div>
{% endblock %}